server:
  port: 8081
  servlet:
    context-path: /hrsys
  compression:
    enabled: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 88888888
    url: jdbc:mysql://localhost:3306/hrsys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: localhost
    database: 0
    port: 6379
    password: 123@456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  cache:
    cache-names: menus_cache
    redis:
      time-to-live: 1800s
  mail:
    host: smtp.qq.com
    protocol: smtp
    username: 1094226429@qq.com
    password: xoazgoiinohobac
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
fastdfs:
  nginx:
    host: http://localhost/
# mybatis打印sql语句日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 启动时打印日志的访问路径
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace
