server:
  port: 8082
spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    username: 1094226429@qq.com
    password: *
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

